# Generated by Django 3.2.12 on 2022-03-19 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_do'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 3, 19)),
        ),
    ]
