# Generated by Django 4.0.3 on 2022-03-21 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_alter_habits_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 3, 21)),
        ),
    ]
