# Generated by Django 4.0.2 on 2022-03-10 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200, null=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('complete', models.BooleanField(null=True)),
                ('priority', models.PositiveSmallIntegerField(choices=[(3, 'Urgent'), (2, 'Important'), (1, 'Normal')])),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.todolists')),
            ],
        ),
    ]
