# Generated by Django 4.0.2 on 2022-03-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Urgent'), (2, 'Important'), (1, 'Normal')], null=True),
        ),
    ]
