# Generated by Django 4.0.2 on 2022-03-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_items_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='complete',
            field=models.BooleanField(default=True),
        ),
    ]
