# Generated by Django 4.0.2 on 2022-03-10 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_items_complete_alter_items_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 21, 1, 20, 720381)),
        ),
    ]
