# Generated by Django 4.0.2 on 2022-03-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_alter_items_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolists',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
